version: '3.8'

# =============================================================================
# Filter-iCal Deployment Configuration
# =============================================================================
# This file defines how filter-ical containers are deployed
# App code lives in: https://github.com/duersjefen/filter-ical
# Images are pulled from GitHub Container Registry
# =============================================================================

networks:
  platform:
    external: true
    name: platform

services:
  # ===========================================================================
  # BACKEND - FastAPI + Python
  # ===========================================================================
  backend:
    container_name: filter-ical-backend${ENVIRONMENT:+-}${ENVIRONMENT}
    image: ghcr.io/duersjefen/filter-ical-backend:${VERSION:-latest}
    restart: unless-stopped
    networks:
      - platform
    env_file:
      - .env.${ENVIRONMENT:-production}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # FRONTEND - Vue 3 SPA
  # ===========================================================================
  frontend:
    container_name: filter-ical-frontend${ENVIRONMENT:+-}${ENVIRONMENT}
    image: ghcr.io/duersjefen/filter-ical-frontend:${VERSION:-latest}
    restart: unless-stopped
    networks:
      - platform
    env_file:
      - .env.${ENVIRONMENT:-production}
    # Healthcheck temporarily disabled for debugging
    healthcheck:
      disable: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"