version: '3.8'

# =============================================================================
# Shared PostgreSQL Database
# =============================================================================
# Shared database server for all platform applications
# =============================================================================

networks:
  platform:
    external: true
    name: platform

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-platform
    restart: unless-stopped
    networks:
      - platform
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-uE3Foa5eJUkh9NQCahsD6E6EMSVjZHu+}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:
    name: platform-postgres-data
