version: '3.8'

# =============================================================================
# Gabs Massage Deployment Configuration
# =============================================================================
# This file defines how gabs-massage containers are deployed
# App code lives in: https://github.com/duersjefen/gabs-massage
# Images are pulled from GitHub Container Registry
# =============================================================================

networks:
  platform:
    external: true
    name: platform

services:
  # ===========================================================================
  # BACKEND - FastAPI + Python
  # ===========================================================================
  backend:
    container_name: gabs-massage-backend${ENVIRONMENT:+-}${ENVIRONMENT}
    image: ghcr.io/duersjefen/gabs-massage-backend:${VERSION:-latest}
    restart: unless-stopped
    networks:
      platform:
        aliases:
          - backend  # Allow DNS resolution by service name
    env_file:
      - .env.${ENVIRONMENT:-production}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # FRONTEND - Vue 3 SPA
  # ===========================================================================
  frontend:
    container_name: gabs-massage-frontend${ENVIRONMENT:+-}${ENVIRONMENT}
    image: ghcr.io/duersjefen/gabs-massage-frontend:${VERSION:-latest}
    restart: unless-stopped
    networks:
      platform:
        aliases:
          - frontend  # Allow DNS resolution by service name
    env_file:
      - .env.${ENVIRONMENT:-production}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s  # Give nginx time to start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
